/*
Copyright 1990-2008 Light Infocon Tecnologia S/A

Este arquivo é parte do programa LightBase - Banco de Dados Textual Documental

O LightBase é um software livre; você pode redistribui-lo e/ou modifica-lo dentro 
dos termos da Licença Pública Geral GNU como publicada pela Fundação do Software 
Livre (FSF); na versão 2 da Licença.

Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA 
GARANTIA; sem uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO 
EM PARTICULAR. Veja a Licença Pública Geral GNU para maiores detalhes.

Você deve ter recebido uma cópia da Licença Pública Geral GNU versao 2, sob o título
"LICENCA.txt", junto com este programa, se não, escreva para a Fundação do Software 
Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
*/

/***********************************************/
// Servidor RPC do LBS
// Macros 
/***********************************************/

#ifndef _DEFMAC_H_
#define _DEFMAC_H_

#define	RPC_BASE_GETFIELDREPETITION_STRING		1
#define	RPC_BASE_GETFIELDREPETITION_VOID		2
#define	RPC_BASE_GETFIELDREPETITION_LONG		3
#define	RPC_BASE_GETFIELDREPETITION_DOUBLE		4
#define	RPC_BASE_GETFIELDREPETITION_BINARY		5
#define	RPC_BASE_GETFIELDREPETITION_REFERENCE	6
#define	RPC_BASE_GETFIELDREPETITION_BYTE		7
#define	RPC_BASE_GETFIELDREPETITION_SHORT		8
#define	RPC_BASE_GETFIELDREPETITION_FLOAT		9
#define	RPC_BASE_GETFIELDREPETITION_DATE		10
#define	RPC_BASE_GETFIELDREPETITION_TIME		11

#define	RPC_BASE_GETFIELDREPETITIONBYVAL_STRING		20
#define	RPC_BASE_GETFIELDREPETITIONBYVAL_VOID		21
#define	RPC_BASE_GETFIELDREPETITIONBYVAL_LONG		22
#define	RPC_BASE_GETFIELDREPETITIONBYVAL_DOUBLE		23  	
#define	RPC_BASE_GETFIELDREPETITIONBYVAL_DATE		24
#define	RPC_BASE_GETFIELDREPETITIONBYVAL_TIME		25
#define	RPC_BASE_GETFIELDREPETITIONBYVAL_BINARY		26
#define	RPC_BASE_GETFIELDREPETITIONBYVAL_REFERENCE	27
#define	RPC_BASE_GETFIELDREPETITIONBYVAL_BYTE		28
#define	RPC_BASE_GETFIELDREPETITIONBYVAL_SHORT		29
#define	RPC_BASE_GETFIELDREPETITIONBYVAL_FLOAT		30

#define	RPC_BASE_PUTFIELDREPETITION_STRING		40
#define	RPC_BASE_PUTFIELDREPETITION_VOID		41
#define	RPC_BASE_PUTFIELDREPETITION_LONG		42
#define	RPC_BASE_PUTFIELDREPETITION_DOUBLE		43 	
#define	RPC_BASE_PUTFIELDREPETITION_DATE		44
#define	RPC_BASE_PUTFIELDREPETITION_TIME		45
#define	RPC_BASE_PUTFIELDREPETITION_BINARY		46
#define	RPC_BASE_PUTFIELDREPETITION_REFERENCE	47
#define	RPC_BASE_PUTFIELDREPETITION_BYTE		48
#define	RPC_BASE_PUTFIELDREPETITION_SHORT		49
#define	RPC_BASE_PUTFIELDREPETITION_FLOAT		50
												
#define	RPC_BASE_PUTFIELDREPETITIONBYINDEX_STRING		60
#define	RPC_BASE_PUTFIELDREPETITIONBYINDEX_VOID			61
#define	RPC_BASE_PUTFIELDREPETITIONBYINDEX_LONG			62
#define	RPC_BASE_PUTFIELDREPETITIONBYINDEX_DOUBLE		63 	
#define	RPC_BASE_PUTFIELDREPETITIONBYINDEX_DATE			64
#define	RPC_BASE_PUTFIELDREPETITIONBYINDEX_TIME			65
#define	RPC_BASE_PUTFIELDREPETITIONBYINDEX_BINARY		66
#define	RPC_BASE_PUTFIELDREPETITIONBYINDEX_REFERENCE	67
#define	RPC_BASE_PUTFIELDREPETITIONBYINDEX_BYTE			68
#define	RPC_BASE_PUTFIELDREPETITIONBYINDEX_SHORT		69
#define	RPC_BASE_PUTFIELDREPETITIONBYINDEX_FLOAT		70
														
#define	RPC_BASE_MODIFYFIELDREPETITION_STRING		80
#define	RPC_BASE_MODIFYFIELDREPETITION_VOID			81
#define	RPC_BASE_MODIFYFIELDREPETITION_LONG			82
#define	RPC_BASE_MODIFYFIELDREPETITION_DOUBLE		83 	
#define	RPC_BASE_MODIFYFIELDREPETITION_DATE			84
#define	RPC_BASE_MODIFYFIELDREPETITION_TIME			85
#define	RPC_BASE_MODIFYFIELDREPETITION_BINARY		86
#define	RPC_BASE_MODIFYFIELDREPETITION_REFERENCE	87
#define	RPC_BASE_MODIFYFIELDREPETITION_BYTE			88
#define	RPC_BASE_MODIFYFIELDREPETITION_SHORT		89
#define	RPC_BASE_MODIFYFIELDREPETITION_FLOAT		90

#define RPC_BASE_GETFIELDTYPE_STRING	1
#define RPC_BASE_GETFIELDTYPE_UINT		2

#define	DATA_OPERATOR_EQUAL_LONG		110
#define	DATA_OPERATOR_EQUAL_DOUBLE		111
#define	DATA_OPERATOR_EQUAL_STRING		112
#define	DATA_OPERATOR_EQUAL_DATE		113
#define	DATA_OPERATOR_EQUAL_TIME		114
#define	DATA_OPERATOR_EQUAL_BINARY		115
#define	DATA_OPERATOR_EQUAL_REFERENCE	116
#define	DATA_OPERATOR_EQUAL_DATA		117
#define	DATA_OPERATOR_EQUAL_BYTE		118
#define	DATA_OPERATOR_EQUAL_SHORT		119
#define DATA_OPERATOR_EQUAL_FLOAT		120
#define DATA_OPERATOR_EQUAL_VOID		121

#define CMPDATANUMBER					300

#endif
